### ISSUE TITLE
the image blocks interaction with the minimap

### ISSUE THREAD

**Issue by dirk-thomas** [negipo/uniq-background#1]
I have the minimap on the right side and the image while supposed to be in the background blocks any interaction with the minimap for the part where the image is displayed.

**Comment by ttaylordev** [comment]
Q: I had a similar issue. I wasn't able to make text selections while the text appeared over the image.
A: In the uniq-background.less add a property to the package styles file.
atom-text-editor::shadow {
     uniq-image {
         pointer-events: none;
         etc...

**Comment by negipo** [comment]
Thank you for notice. I will investigate about this.
